# Generated by the vetiver package; edit with care

FROM rocker/r-ver:4.4.2

# Create non-root user
RUN useradd --create-home appuser

# Set environment variables
ENV RENV_CONFIG_REPOS_OVERRIDE https://packagemanager.rstudio.com/cran/latest
ENV HOME=/home/appuser
ENV RENV_PATHS_LIBRARY /home/appuser/renv/library

WORKDIR $HOME

# Install system dependencies (including XGBoost requirements)
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
  libcurl4-openssl-dev \
  libicu-dev \
  libsodium-dev \
  libssl-dev \
  libx11-dev \
  libxml2-dev \
  libfontconfig1-dev \
  libharfbuzz-dev \
  libfribidi-dev \
  libfreetype6-dev \
  libpng-dev \
  libtiff5-dev \
  libjpeg-dev \
  make \
  zlib1g-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Copy renv lockfile and restore packages
COPY vetiver_renv.lock renv.lock
RUN Rscript -e "install.packages('renv', repos='https://cran.rstudio.com/')"
RUN Rscript -e "renv::restore()"

# Copy model data and API code
ADD my-pins /data/my-pins
COPY plumber.R /opt/ml/plumber.R

# Change ownership to appuser
RUN chown -R appuser:appuser /home/appuser /data /opt/ml

# Switch to non-root user
USER appuser

# Expose port
EXPOSE 7860

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD curl -f http://localhost:7860/ping || exit 1

# Start the application
ENTRYPOINT ["R", "-e", "pr <- plumber::plumb('/opt/ml/plumber.R'); pr$run(host = '0.0.0.0', port = 7860)"]